on:
  push:
    branches:
      - develop
      - main

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Export project name
        run: export PROJECT_NAME=$(echo ${{ github.repository }} | cut -d / -f2); echo $PROJECT_NAME

      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.K8CLUSTER_NAME }}

      - name: Deploy to k8 cluster
        run: |
          export PROJECT_NAME=$(echo ${{ github.repository }} | cut -d / -f2)
          helm repo add sonam https://sonamsamdupkhangsar.github.io/sonam-helm-chart/
          helm upgrade --install --timeout 5m0s \
            --set "image.repository=pactfoundation/pact-broker" \
            --set "image.tag=latest" \
            --set "project=$PROJECT_NAME" \
            --set "postgres.secretfile=${{ secrets.POSTGRES_SECRET_FILE }}" \
            --set "postgres.service=${{ secrets.POSTGRES_SERVICE }}" \
            --set "postgres.dbname=${{ secrets.POSTGRES_DBNAME }}" \
            --set "secretenvs[0].name=PACT_BROKER_BASIC_AUTH_USERNAME" --set "secretenvs[0].value=${{ secrets.PACT_BROKER_BASIC_AUTH_USERNAME }}" \
            --set "secretenvs[1].name=PACT_BROKER_BASIC_AUTH_PASSWORD" --set "secretenvs[1].value=${{ secrets.PACT_BROKER_BASIC_AUTH_PASSWORD }}" \
             $PROJECT_NAME \
            sonam/mychart -f values-backend.yaml --version 0.1.14 --namespace=backend